- name: 'Disable automatic updates'
  become: true
  command: "{{ item }}"
  with_items:
  - systemctl stop apt-daily.service
  - systemctl stop apt-daily.timer
  - systemctl kill --kill-who=all apt-daily.service

- name: 'Add support for PPAs'
  become: true
  action: apt pkg={{item}} state=installed update-cache=yes
  with_items:
    - software-properties-common
    - python-software-properties
    - build-essential

- name: 'Install aptitude'
  become: true
  apt:
    name: aptitude

- name: 'Install python-pexpect'
  become: true
  apt:
    name: python-pexpect

- name: 'Install git'
  become: true
  apt:
    name: git

- name: 'Install tmux'
  become: true
  apt:
    name: tmux

- name: 'Create /home/vagrant/Desktop/'
  file:
    path: /home/vagrant/Desktop
    state: directory
    mode: 0755
