- name: 'Disable automatic updates'
  become: true
  command: "{{ item }}"
  with_items:
  - systemctl stop apt-daily.service
  - systemctl stop apt-daily.timer
  - systemctl kill --kill-who=all apt-daily.service
  
- name: 'Add support for PPAs'
  become: true
  action: apt pkg={{item}} state=installed update-cache=yes
  with_items:
    - software-properties-common
    - python-software-properties

- name: 'Install aptitude'
  become: true
  apt:
    name: aptitude

- name: 'Install python-pexpect'
  become: true
  apt:
    name: python-pexpect

- name: 'Install git'
  become: true
  apt:
    name: git

- name: 'Upgrade all packages'
  become: true
  apt:
    upgrade: yes
    update-cache: yes
