- name: 'Disable automatic updates'
  become: true
  command: "{{ item }}"
  with_items:
  - systemctl stop apt-daily.service
  - systemctl stop apt-daily.timer
  - systemctl kill --kill-who=all apt-daily.service

- name: 'install python2'
  become: true
  raw: apt-get -y install python-simplejson

- name: 'install aptitude'
  become: true
  raw:  apt-get -y install aptitude

- name: 'Add support for PPAs'
  become: true
  action: apt pkg={{item}} state=installed update-cache=yes
  with_items:
    - software-properties-common
    - python-software-properties
    - build-essential

- name: 'Install python-pexpect'
  become: true
  apt:
    name: python-pexpect

- name: 'Install git'
  become: true
  apt:
    name: git

- name: 'Install tmux'
  become: true
  apt:
    name: tmux

- name: 'Install tree'
  become: true
  apt:
    name: tree

- name: 'Install nano'
  become: true
  apt:
    name: nano

- name: 'Install Chromium'
  become: true
  apt:
    name: chromium-browser

- name: 'Create /home/vagrant/Desktop/'
  file:
    path: /home/vagrant/Desktop
    state: directory
    mode: 0755

- name: 'Create /home/vagrant/Downloads/'
  file:
    path: /home/vagrant/Downloads
    state: directory
    mode: 0755
