# install this software? Y
# install and configure a Netstats client? n

- name: 'Download Parity install script'
  get_url:
    url: https://get.parity.io
    dest: ~/install_parity.sh
    mode: 0740

- name: 'Install Parity'
  expect:
    command: ./install_parity.sh
    responses:
      (?i)software:
        - 'Y'
      (?i)Netstats:
        - 'n'
        - 'n'

- name: 'Add Parity script to Desktop'
  copy:
    src: '{{ role_path }}/files/run-parity.sh'
    dest: '/home/{{ ansible_ssh_user }}/Desktop/run-parity.sh'
    mode: 0744
